### ISSUE TITLE
Ability to mock no connection to server

### ISSUE THREAD

**Issue by Amertz08** [jamesls/fakeredis#102]
I think it would be useful to mock the errors thrown when you are unable to connect to the redis server. It appears that redis-py throws a `ConnectionError` with these args `('Error 61 connecting to localhost:6379. Connection refused.',)` when it cannot reach the server.

**Comment by jamesls** [comment]
Seems reasonable.  Is someone willing to propose what the API for this would look like?

**Comment by Amertz08** [comment]
```python
class FakeStrictRedis(object):
    CONNECTED = TRUE

    def set(*args):
        if not self.CONNECTED:
            raise ConnectionError('Error 61 connecting to localhost:6379. Connection refused.')
        else:
            # proceed as normal
```

Just an example I guess. Would need to look at the entire redis-py lib

**Comment by Amertz08** [comment]
2 years after the fact I've decided I'd give this a shot. [Here](https://github.com/jamesls/fakeredis/compare/master...Amertz08:102-mock-connection-error) is what I have so far
