### ISSUE TITLE
randomkey method is not implemented, but is not in the list of unimplemented commands

### ISSUE THREAD

**Issue by Jwpe** [jamesls/fakeredis#106]
Relevant code:

https://github.com/jamesls/fakeredis/blob/master/fakeredis.py#L356

Relevant documentation:

https://github.com/jamesls/fakeredis#unimplemented-commands

There's a discrepancy here. Would it be better to implement the `randomkey` method, or just add it to the list of unimplemented commands?

**Comment by thedrow** [comment]
Why not implement it?

**Comment by jamesls** [comment]
Sorry for the delay.  I'd prefer to implement.  Might be difficult to write a reliable unit test for this, but it would be great to have this implemented.

**Comment by bmerry** [comment]
Fixed by removing the stub implementations and adding to the list of unimplemented commands. An implementation would still be welcome.
