### ISSUE TITLE
setex arguments time and value are inverted

### ISSUE THREAD

**Issue by nbigot** [jamesls/fakeredis#117]
Hi,

It seems that some arguments (time and value) order are inverted for the setex function.
I got an error when using fakeredis version 0.7.0

Using **redis-py**:

```
import redis
# ...
r.setex('mykey', 'myvalue', 10)
```

Using **fakeredis version 0.7.0**

```
import fakeredis
r = fakeredis.FakeStrictRedis()
r.setex('mykey', 10, 'myvalue')
```

Can actually be overcome by naming the args:
```
import redis
r.setex(name='mykey', value='myvalue', time=10)
```

But it would be cool if it can have the same order for the args.
What do you think?

Regards.

**Comment by jamesls** [comment]
What version of `redis-py` are you using?

The args from [redis-py](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1174) seem to match up with how fakeredis defines [setex](https://github.com/jamesls/fakeredis/blob/master/fakeredis.py#L478)

**Comment by nbigot** [comment]
Hi, 

Sorry, my fault.

I used your FakeStrictRedis class in front of the Redis class instead of the StrictRedis class

(I'm using the version redis 2.10.5)

I realized that there are two classes : 

- StrictRedis
- Redis (which seems to be the legacy one)

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L342
`class StrictRedis(object):`

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1174
`def setex(self, name, time, value):`

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2197
`class Redis(StrictRedis):`

>     Provides backwards compatibility with older versions of redis-py that
>     changed arguments to some commands to be more Pythonic, sane, or by
>     accident.



https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2227
`def setex(self, name, value, time):`

Regards.

**Comment by nbigot** [comment]
was not a bug
