### ISSUE TITLE
FakeStrictRedis ttl should not return None

### ISSUE THREAD

**Issue by marakal** [jamesls/fakeredis#119]
StrictRedis' ttl and pttl methods return -1 when expire is not set and -2 when key does not exist ([documentation of python redis](https://pypi.python.org/pypi/redis), [documentation of redis](http://redis.io/commands/ttl)), but FakeStrictRedis' methods return None instead.

```
In [1]: r = redis.StrictRedis(db=0)

In [2]: r.ttl("foo")
Out[2]: -2

In [3]: f = fakeredis.FakeStrictRedis()

In [4]: f.ttl("foo")
Out[4]: None
```

**Comment by EricCline** [comment]
+1

**Comment by gazoon** [comment]
+1

**Comment by jamesls** [comment]
Fixed via https://github.com/jamesls/fakeredis/pull/134
