### ISSUE TITLE
ConnectionPool mock isn't implemented

### ISSUE THREAD

**Issue by z0rc** [jamesls/fakeredis#122]
My code uses single `redis.ConnectionPool` across multiple threads, pool is passed as a parameter to thread function. I'd like to be able to test this function with `fakeredis`, but since ConnectionPool mock is missing, I'm stuck with using real redis-server (temporary created as docker container during tests).

**Comment by jamesls** [comment]
Could you give a code sample of how you use `ConnectionPool`.  Want to make sure I understand what's being requested.

**Comment by z0rc** [comment]
Basically I have something like this:
```python
import redis
import threading


def test_thread(redis_pool):
    r = redis.StrictRedis(connection_pool=redis_pool)
    r.ping()


redis_pool = redis.ConnectionPool(host='127.0.0.1', port=6379)

for i in range(1, 5):
    test_worker = threading.Thread(target=test_thread, args=(redis_pool, ))
    test_worker.start()
    test_worker.join()
```

And I hoped to test `test_thread` using the mock from fakeredis.

**Comment by bmerry** [comment]
If you're working on Linux then [birdisle](http://birdisle.readthedocs.io/) might solve your problem. It slots into redis at a lower level than fakeredis, so you can have an actual `redis.ConnectionPool`, just constructed with different arguments. It's not well documented, but see [this code](https://github.com/bmerry/birdisle-py/blob/8c1d31aa988f810423fcdf207af34900b942f667/birdisle/redis.py#L81-L93) in the implementation for how to construct such a connection pool.

**Comment by bmerry** [comment]
As of 1.0b1, you should be able to do it like this:
```
dummy_redis = fakeredis.FakeStrictRedis()
redis_pool = dummy_redis.connection_pool
```
I'm going to close, but reopen if that doesn't work for you.

**Comment by bmerry** [comment]
And once 1.0 is released you'll also be able to do
```python
redis_pool = redis.ConnectionPool(
    connection_class=fakeredis.FakeConnection,
    server=fakeredis.FakeServer())
```
