### ISSUE TITLE
Empty sets still exist

### ISSUE THREAD

**Issue by tapple** [jamesls/fakeredis#155]
sets that have every element removed should answer False to exists, and should not be returned by keys or scan. However, they do. I don't know if sorted sets, lists, hashes, or strings also have this problem

In [1]: import fakeredis
In [2]: import redis
In [3]: r = fakeredis.FakeStrictRedis()
In [4]: r.sadd('s', 1)
Out[4]: 1
In [5]: assert r.exists('s')
In [8]: assert b's' in r.keys()
In [9]: r.srem('s', 1)
Out[9]: 1
In [10]: assert not r.exists('s')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

In [11]: assert b's' not in r.keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

In [12]: r = redis.StrictRedis()
In [13]: r.sadd('s', 1)
Out[13]: 1
In [14]: assert r.exists('s')
In [15]: assert b's' in r.keys()
In [16]: r.srem('s', 1)
Out[16]: 1
In [17]: assert not r.exists('s')
In [18]: assert b's' not in r.keys()
In [19]:

**Comment by fjsj** [comment]
Confirm the issue. This breaks one of my algorithms :(
Both redis-cli and StrictRedis return False for empty sets if you call `exists`.

The correct behavior:
```
$ redis-cli
127.0.0.1:6379> del my_set
(integer) 0
127.0.0.1:6379> sadd my_set 1
(integer) 1
127.0.0.1:6379> spop my_set
"1"
127.0.0.1:6379> exists my_set
(integer) 0
```
