### ISSUE TITLE
Publish changelog

### ISSUE THREAD

**Issue by peterbe** [jamesls/fakeredis#162]
Would be wonderful to have a change log as versions increment. For example, pyup made [a PR on my repo](https://github.com/mozilla-services/tecken/pull/473) and it fails the include a change log for going from 0.8.2 to 0.9.0. The tests fail and now I need to dig through the commit history to find what might be the reason.

**Comment by bmerry** [comment]
I've started a changelog from 0.9.0 onwards. If you need a changelog going further backwards I think your best chance is to write it yourself and submit a PR.
