### ISSUE TITLE
Import fails on osx, says it cannot find libc or msvcrt

### ISSUE THREAD

**Issue by shaleh** [jamesls/fakeredis#188]
libc.dylib exists but ctypes skips it. Possibly because it is a symlink.

I added `find_library('System')` which is what libc links to and the import worked.

**Comment by bmerry** [comment]
@ludwigschwardt have you had any problems with this?

**Comment by ludwigschwardt** [comment]
I have no such problem on macOS 10.11.6 using Homebrew Python 2.7 or 3.6.

My libc is also a symlink and is picked up fine:

```
lrwxr-xr-x  1 root  wheel  15 Jan  5  2016 /usr/lib/libc.dylib -> libSystem.dylib
```

**Comment by shaleh** [comment]
I am on 10.13.3. Python 2.7.14 (also from brew).

**Comment by bmerry** [comment]
@shaleh does #189 fix this for you?

**Comment by shaleh** [comment]
That is exactly how I fixed it locally.
