### ISSUE TITLE
BLPOP does not block

### ISSUE THREAD

**Issue by irvinlim** [jamesls/fakeredis#196]
I'm not sure if fakeredis is supposed to block on `BLPOP` if there are no elements to pop, as mentioned here: https://redis.io/commands/blpop

I've created a very simple repro [here](https://github.com/irvinlim/fakeredis-repro), which you can see that fakeredis returns immediately and does not wait until the `timeout` set, as follows:

```python
redis = StrictRedis(**config)
fakeredis = FakeStrictRedis()
redis.flushall()
fakeredis.flushall()

print '[+] FakeRedis BLPOP:'
now = time()
popped = fakeredis.blpop('hello_world', 10)
print '[*] Took %.2f seconds' % (time() - now)
print '[*] Popped value:', popped
print

print '[+] Redis BLPOP:'
now = time()
popped = redis.blpop('hello_world', 10)
print '[*] Took %.2f seconds' % (time() - now)
print '[*] Popped value:', popped
```

Output:

```
[+] FakeRedis BLPOP:
[*] Took 0.00 seconds
[*] Popped value: None

[+] Redis BLPOP:
[*] Took 10.03 seconds
[*] Popped value: None
```

After reading the [source](https://github.com/jamesls/fakeredis/blob/5bd2f1b1498633c73fd99762be78e6ebf02a728e/fakeredis.py#L1143), it seems that the `timeout` argument is not being used in any way for `blpop`, `brpop` and `brpoplpush`, nor does it sleep or wait indefinitely if no timeout is set, unlike a real Redis connection.

Is this intentional or an oversight?

**Comment by bmerry** [comment]
I'm not the original author, but my impression is that fakeredis has very little support for operations that involve synchronisation. In particular, it is not thread-safe, and a blocking BLPOP necessarily involves multiple threads. Unfortunately fakeredis doesn't currently have a maintainer with the time to invest in major overhauls.

**Comment by irvinlim** [comment]
@bmerry Indeed, it seems so after digging through the source for a bit. I wouldn't have expected it to be thread-safe since it's a mock anyway, but not using the `timeout` parameter was surprising. However now that you mention it, it makes sense I guess.
