### ISSUE TITLE
Why zadd incompatible with either redis-py or mockredis

### ISSUE THREAD

**Issue by qwIvan** [jamesls/fakeredis#198]
redis-py:
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1688

mockredis:
https://github.com/locationlabs/mockredis/blob/99fc1af668a0872262a00752800bdacb168dd0ee/mockredis/tests/test_scan.py#L197-L208

fakeredis:
https://github.com/jamesls/fakeredis/blob/5bd2f1b1498633c73fd99762be78e6ebf02a728e/test_fakeredis.py#L1610-L1622

**Comment by bmerry** [comment]
Sorry, I don't understand what the problem is. You've highlighted some bits of code, but not said what's wrong with any of it. Can you say
- What you tried to do
- What happened
- What you expected to happen

I wasn't aware that mockredis existed. Thanks for letting me know about it.

**Comment by bmerry** [comment]
I think perhaps you're confusing redis.Redis and redis.StrictRedis. The former takes name, score while the latter takes score, name. fakeredis.FakeStrictRedis simulates redis.StrictRedis while fakeredis.FakeRedis simulates redis.Redis.

**Comment by wenbochang** [comment]
Just ran into this, thank you!

**Comment by qwIvan** [comment]
@bmerry thanks
