### ISSUE TITLE
Drop Python 2.6 support?

### ISSUE THREAD

**Issue by thedrow** [jamesls/fakeredis#206]
Python 2.6 is very old.
If people need it, they can use previous versions.

What do you think?

**Comment by hugovk** [comment]
Drop it and Python 3.3.

They're both EOL and longer receiving security updates (or any updates) from the core Python team.

They're also little used. Here's the pip installs for fakeredis from PyPI for July 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  43.69% |         15,102 |
| 3.6            |  30.85% |         10,661 |
| 3.5            |  14.93% |          5,160 |
| 3.4            |   9.40% |          3,249 |
| 3.7            |   1.06% |            368 |
| 2.6            |   0.05% |             17 |
| 3.3            |   0.02% |              6 |
| Total          |         |         34,563 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown fakeredis pyversion`

**Comment by hugovk** [comment]
Please see PR https://github.com/jamesls/fakeredis/pull/210.

**Comment by bmerry** [comment]
Implemented as of 1.0b1.
