### ISSUE TITLE
purpose of the project

### ISSUE THREAD

**Issue by tmbdev** [jamesls/fakeredis#221]
I'm writing machine learning software that can work both distributed and local, and for local execution, being able to use the Redis API without a server is nice.

I wanted to suggest updating the mission statement of the project. Right now it says "This was created for a single purpose: to write unittests." It would be nice if the mission statement could explicitly acknowledge other serverless applications of fakeredis. It doesn't really make a practical difference, but it may remind developers to at least keep such use cases in mind.

So, maybe say "Fakeredis is useful in situations where software written to the Redis API must be used in an environment where a Redis server cannot be started. This occurs commonly for unit-testing, but also some application software."

**Comment by bmerry** [comment]
If it works for your use-case, that's great, but I don't want people to have false expectations about its suitability, particularly with regards to performance scaling. For example, some operations that take O(log N) time in redis take O(N) time (or possibly worse) in fakeredis.
