### ISSUE TITLE
__delitem__ missing

### ISSUE THREAD

**Issue by viljoviitanen** [jamesls/fakeredis#223]
Noticed fakeredis does not support "del" operator, i.e. it does not implement `__delitem__` , while real redis does.

So code like this works on real redis:
```python
import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0)
r['foo'] = 'bar'
print (r['foo'])  #bar
del r['foo']
print (r['foo'])  #KeyError: 'foo'
```
but fails on fakeredis:
```python
import fakeredis
r = fakeredis.FakeStrictRedis()
r['foo'] = 'bar'
print (r['foo'])  #bar
del r['foo']      #AttributeError: __delitem__
#r.delete('foo')  #this would work
```

My guess on this is that even if  `__delitem__` is there in _StrKeyDict, because of name mangling, this happens.

If there's interest in getting this fixed, I can probably do a clean enough PR.

**Comment by bmerry** [comment]
> If there's interest in getting this fixed, I can probably do a clean enough PR.

Yes, PRs are very welcome. I'm guessing it should be a pretty thin wrapper around `.delete`.
