### ISSUE TITLE
client.register_script seems to be missing since redis-py 3.0.0

### ISSUE THREAD

**Issue by ticosax** [jamesls/fakeredis#226]
Can be triggered when attempting to create a `redis.lock.Lock`

https://github.com/andymccurdy/redis-py/commit/255f01036f6a8d10b4369eca9e491d13d3c3788a

**Comment by bmerry** [comment]
fakeredis doesn't yet support redis-py 3. I will probably make a release soon which explicitly depends on older versions. I'm investigating a redesign of fakeredis that will make it somewhat independent of the redis version, but it will probably only be ready next year.
