### ISSUE TITLE
Remove six?

### ISSUE THREAD

**Issue by knyghty** [jamesls/fakeredis#238]
It seems like since you took out Python 3 support, there's no reason to use six anymore. The reason I mention this is I can't use this package because the version of six required conflicts with other packages.

Is there some reason six is still used here? Happy to provide a PR for this.

**Comment by bmerry** [comment]
What makes you say Python 3 support has been removed? It still supports Python 2 and 3 and is tested with both on Travis.

Perhaps you could get the other packages to fix their conflict with six? six is used by a *lot* of projects, including major ones like pytest, tox, cryptography and packaging, so I think it is reasonable to expect other packages to be able to work with it.

**Comment by knyghty** [comment]
This commit message suggests it: https://github.com/jamesls/fakeredis/commit/e93e709963282bba3bd198dfda811bb852e1d689

If that commit message is misleading then I'll try to find another way around it.

The conflict is not with six, but with the specific version of six required by different packages, often people pin stuff a bit too aggressively and it leads to conflicts during dependency resolution when using tools like pipenv or pip-tools.

**Comment by bmerry** [comment]
There's a typo in the commit message: it should say 2.6 and 3.3. Python 2.7 and 3.4+ are still supported.
