### ISSUE TITLE
delete while scanning doesn't match redis behaviour

### ISSUE THREAD

**Issue by Amir-Hadadi** [jamesls/fakeredis#239]
scan_iter runs on just half the keys if they are updated (delete/rename) while iterated on. unlike real redis..

[fakeredis.txt](https://github.com/jamesls/fakeredis/files/3343068/fakeredis.txt)

fakeredis 1.0.3

**Comment by bmerry** [comment]
Yes, that limitation is documented [here](https://github.com/jamesls/fakeredis#other-limitations). Trying to make scan-like commands interact properly with every other command that modifies the structure being scanned was more effort than I had time for.

**Comment by bmerry** [comment]
I'm going to close this because it's documented in the README, and I generally don't duplicate those limitations (described as "differences that are unlikely to ever be fixed") as Github issues. That doesn't mean I wouldn't accept a pull request.

**Comment by Amir-Hadadi** [comment]
OK, thanks.
Actually, i started seeing the problem when RENAMEing while SCANning, and i didn't find anything about renaming problems, and only later after trying more stuf like deleting i thought that's more of a general case.. so maybe add a mention for rename in that documentation? or you think it's obvious that deletion bugs affect renames..

**Comment by bmerry** [comment]
It's a fair point. I've updated the README to say "deleted or renamed".

**Comment by bmerry** [comment]
Closing without fixing for the reason described in [this comment](https://github.com/jamesls/fakeredis/issues/239#issuecomment-507129749).
