### ISSUE TITLE
Support UNLINK command

### ISSUE THREAD

**Issue by zsblevins** [jamesls/fakeredis#249]
Swapping calls from delete to unlink yields:
`redis.exceptions.ResponseError: Command # 1 (UNLINK <key>) of pipeline caused error: unknown command 'UNLINK'`

**Comment by zsblevins** [comment]
Why it's worth implementing: https://redislabs.com/blog/the-little-known-feature-of-redis-4-0-that-will-speed-up-your-applications/ 

I can patch it in my tests as needed if there is no plan on implementing it

**Comment by bmerry** [comment]
I don't currently have any plans to implement it (because I have very little time to spend on fakeredis), but on the other hand I think it should be very easy to implement since it can just call `del_`. I'd be happy to review a pull request.

**Comment by zsblevins** [comment]
Here you go! https://github.com/jamesls/fakeredis/pull/250
