### ISSUE TITLE
fakeredis does not support all the redis connection arguments

### ISSUE THREAD

**Issue by nateyoder** [jamesls/fakeredis#255]
Some unsupported arguments include socket_timeout, socket_connect_timeout, socket_keepalive, socket_keepalive_options, socket_type, retry_on_timeout, socket_read_size and health_check_interval. While I wouldn't expect this to necessarily be simulated by fakeredis it would be nice to be able to use this in the from_url command.

Ex: FakeRedis.from_url(redis_url, db=None, socket_connect_timeout=5, socket_timeout=30)

**Comment by bmerry** [comment]
Unfortunately I don't have much time to work on fakeredis at the moment, but I'd be happy to review a pull request to add this.
