### ISSUE TITLE
Add note on how to get default server

### ISSUE THREAD

**Issue by penguindustin** [jamesls/fakeredis#256]
I use pytest and mock out redis in a fixture. One of the handy things fakeredis does is provide a way to programmatically mock connection errors. I think it would nice to note how to get the fake server instance in the case where you don't provide a server yourself. I can also do a PR for this is wanted, if not feel free to close this issue.

**Comment by bmerry** [comment]
I'm not quite sure what you mean, so maybe make a PR and then I'll also understand what you're suggesting. More documentation is generally good - the only reason I wouldn't want it is if it's documenting internals that I don't want to commit to supporting as a stable public API.

**Comment by penguindustin** [comment]
Just made a PR, hopefully it clarifies things.

**Comment by bmerry** [comment]
Closing without fixing for reasons explained in #258.
