### ISSUE TITLE
Inconsistent HSET behaviour with booleans in Lua

### ISSUE THREAD

**Issue by upcFrost** [jamesls/fakeredis#269]
Hi,

Found an inconsistent behaviour of fakeredis when using HSET and booleans. See the script below

```python
import fakeredis
redis = fakeredis.FakeStrictRedis()
call = redis.register_script('redis.call("HSET", "mykey", "luavalue", true)')
call()
redis.hget("mykey", "luavalue")
# b'1'
```

Real redis:
```
127.0.0.1:6379> eval 'redis.call("HSET", "mykey", "test_value", true)' 0
(error) ERR Error running script (call to f_100352cfb27b6960ee5471ec9b8f92fed22e57df): @user_script:1: @user_script: 1: Lua redis() command arguments must be strings or integers
```

With redis-py fails as well

Redis 6.0.3
Fakeredis 1.4.1

**Comment by bmerry** [comment]
Thanks for the report. I've fixed it, but my current plan is not to make a new release immediately because it's pretty easy to work around (even if frustrating when it leads to failures in production). Let me know if it's actually a blocker for some reason.

**Comment by upcFrost** [comment]
Thanks! It's not a blocker of any kind, just a small issue found during the test.
