### ISSUE TITLE
test_time test is failing

### ISSUE THREAD

**Issue by murraybd** [jamesls/fakeredis#282]
https://github.com/jamesls/fakeredis/blob/dcf0c8933fff7b3e0f08879a9905dea4f67ca750/test/test_fakeredis.py#L3362

The test "test_time" is failing in Ubuntu with the following error:

==================================== ERRORS ====================================
_________________ ERROR at setup of test_time[FakeStrictRedis] _________________
file /tmp/autopkgtest.czefjb/build.rUT/src/test/test_fakeredis.py, line 3361
  @fake_only
  def test_time(r, mocker):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, create_redis, doctest_namespace, fake_server, is_redis_running, monkeypatch, no_cover, pytestconfig, r, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/tmp/autopkgtest.czefjb/build.rUT/src/test/test_fakeredis.py:3361

From https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/amd64/p/python-fakeredis/20200907_120238_a7fd0@/log.gz

I believe this is because "test_time" because something else has a fixture named "test_time". I was able to get the test to pass by simply renaming it to "def mytest_time". This helped me figure out to rename the test.

https://github.com/pytest-dev/pytest-mock/issues/70

**Comment by bmerry** [comment]
From the error message it seems more likely that you don't have pytest-mock installed. I'm not sure if there is a good way to declare pytest plugin dependencies so that pytest will give a helpful error.

**Comment by murraybd** [comment]
That certainly seems to be the case. Sorry for the trouble!
