### ISSUE TITLE
Adding support for full text search

### ISSUE THREAD

**Issue by kingbuzzman** [jamesls/fakeredis#284]
https://github.com/RediSearch/redisearch-py

Would you be open to a PR?

**Comment by bmerry** [comment]
I appreciate the offer to do the work, but I'm also hesitant to expand fakeredis to start emulating the wider ecosystem when I don't really have enough time to maintain it as is.

I know very little about the redis module system, but do you think it would be feasible to make a separate fake-redisearch package, which could evolve at its own pace? If that needs changes to fakeredis to provide hooks for integration I'd be more willing to accept PRs for that.

**Comment by kingbuzzman** [comment]
Fair enough, I understand your position. Thank you for the reply.
