### ISSUE TITLE
Loading a dump.rdb at server init

### ISSUE THREAD

**Issue by kennedy** [jamesls/fakeredis#288]
hello,
I am still very new to redis. Im working on a project where a production spin-up, a redis-server would pre-load a dump.rdb. The file is fetched prior to starting the server.
```
redis-server --dbfilename dump.rdb --dir /data
```
Is there a way to use fakeredis to handle this use-case?

If not, one strategy I'm investigating is for-looping through the dumpfile and loading each key.

**Comment by bmerry** [comment]
There is no support for this in fakeredis itself, but it's not too hard to implement something like this using [rdbtools](https://pypi.org/project/rdbtools/) to populate the database one key at a time, particularly if you're not using all the different key types that redis supports.

**Comment by kennedy** [comment]
sounds good, thanks!
