### ISSUE TITLE
how do you access the internal state as a dictionary?

### ISSUE THREAD

**Issue by bionicles** [jamesls/fakeredis#291]
i'd like to pickle snapshots of test results so i can run multiple downstream tests independently, but i'm not entirely sure how to do this.

I thought fakeredis was just a subclass of dictionary which implemented the redis commands, but there's like 4 layers of connection pools, connections, servers, databases, keys, and i'm not entirely sure how to just get a dictionary of the current state of the database.

how would it be possible to get the current state of a fakeredis client as a dict so I can pickle it?

**Comment by bmerry** [comment]
A Redis server has a lot more state than just keys and values - there are expiry times, transactions, watches, pub/sub, configuration, and probably more.

If you only care about the keys and values, then the simplest way to extract it is probably
```python
data = {key: r.dump(key) for key in r.keys()}
```
which you could then pickle or persist in some other way. Then use `restore` to load it again.

Note that fakeredis doesn't yet use the proper redis encoding for the DUMP command and it is subject to change in future versions. If you're generating dumps in one part of a test pipeline and consuming them later in the same test pipeline that shouldn't be a problem, but don't treat them as long-term test assets.

**Comment by bionicles** [comment]
thank you! i wound up just writing a big test function for a bunch of units in a row using the same fakeredis instance and it worked like a charm!
