### ISSUE TITLE
Redisgraph support

### ISSUE THREAD

**Issue by ljvmiranda921** [jamesls/fakeredis#294]
Hi devs!

Thank you for this wonderful package. I'd like to know how I can use fakeredis to mock redisgraph. I'm currently using this [library client](https://github.com/RedisGraph/redisgraph-py) in python and my use-case is as follows:

```python
# app code
import redis
import redisgraph

client = redis.Redis()
graph = redisgraph.Graph("MyGraph", client)
```

And on test:

```python
# test code
import fakeredis
import redisgraph

fake_client = redis.FakeRedis()
graph = redisgraph.Graph("MyGraph, fake_client)
```

However, it raises an `UNKNOWN_COMMAND_ERROR`. Perhaps it's because the fakeredis API doesn't support redisgraph. I'd like to know how I can update the code (and maybe contribute to this project) to incorporate and mock redisgraph

**Comment by bmerry** [comment]
Faking add-on redis modules is unfortunately outside the scope of fakeredis.
