### ISSUE TITLE
Deadlock triggered by RQ with a scheduler

### ISSUE THREAD

**Issue by detzgk** [jamesls/fakeredis#297]
When running RQ with its scheduler enabled, we inevitably deadlock because a Connection object is collected while the main server lock is being held by the command processor. This reliably triggers it in a matter of seconds.

```python
import fakeredis
import rq

import footoo

connection = fakeredis.FakeStrictRedis()
queue = rq.Queue("Q", is_async=False, connection=connection)


while True:
    queue.enqueue(footoo.what)
    worker = rq.SimpleWorker(queues=[queue], connection=connection)
    worker.work(burst=True, with_scheduler=True)
```

(It doesn't matter what footoo.what does, it just needs to be outside the `__main__` module so RQ can refer to it).

It is caused because at some point a `Connection` object is being finalized and its `__del__` method calls the `FakeSocket.close` method which tries to acquire a lock that's already being held.

A very easy fix is to replace the `server.lock` with a `threading.RLock`. This doesn't cause any test failures but I'm not sure how thoroughly concurrency is tested. It seems likely to cause problems for people using cooperative threading models, like AIO, where multiple tasks running on the same thread will be permitted to acquire the RLock even though they should be exclusive.

**Comment by bmerry** [comment]
@detzgk see if the linked PR solves your problem.

**Comment by detzgk** [comment]
It's working! I added some comments to the PR, I'm not sure it's 100% right.
