### ISSUE TITLE
FakeStrictRedis does not support health_check_interval as an init kwarg

### ISSUE THREAD

**Issue by jonblum** [jamesls/fakeredis#311]
Redis-py's client accepts `health_check_interval` as an init keyword argument, which is then passed onto its connection pool:
https://github.com/redis/redis-py/blob/3.5.3/redis/client.py#L699-L711

Currently, it appears that `FakeStrictRedis` does not accept this kwarg, leading to errors if you try to swap in `FakeStrictRedis` for a redis-py `Redis` client instance in code where `health_check_interval` is used.

**Comment by jonblum** [comment]
Sorry for the delay, but yes, it does.  Thank you!

**Comment by bmerry** [comment]
This is included in the 1.7.0 release, so closing.
