### ISSUE TITLE
support redis 4.0.0

### ISSUE THREAD

**Issue by AH012** [jamesls/fakeredis#321]
Hello !

May I know please when the support for redis 4.0.0 will be available ?

Thank you in advance

**Comment by bmerry** [comment]
I'm working on it at the moment - unfortunately there were some changes from 4.0.0rc2 which broke fakeredis again. I'm aiming to have a release in a week or two.

If you're in a hurry you can try the prepare-1.7 branch.

**Comment by AH012** [comment]
Okay thank you ! 

Good luck

**Comment by bmerry** [comment]
fakeredis 1.7.0 now supports redis 4.
