### ISSUE TITLE
Add support for redis-py 4.2.0

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [jamesls/fakeredis#329]
It would be great to have support for the new release of redis-py, that now includes also aioredis.

I've tried to install it, but I've got the following compatibility error

```
pip install fakeredis==1.7.1
...
The conflict is caused by:
    <my_package> depends on redis>=4.2.0
    fakeredis 1.7.1 depends on redis<4.2.0

```

**Comment by cunla** [comment]
Fixed on v1.7.4 published from here: https://github.com/dsoftwareinc/fakeredis-py.
@bmerry this can be closed

**Comment by bmerry** [comment]
fakeredis 1.7.4 now supports redis-py 4.2.2.

**Comment by ca-simone-chiorazzo** [comment]
Awesome! Thanks :)
