### ISSUE TITLE
RFE: provide support for latest `redis` 4.2.2

### ISSUE THREAD

**Issue by kloczek** [jamesls/fakeredis#331]
https://github.com/jamesls/fakeredis/blob/0303b2ddfa4d6cd5098a0a29b23d300296307c59/setup.cfg#L24-L29
Yep .. it would be nice to have such support 😃

**Comment by bmerry** [comment]
I believe 1.7.4 now supports 4.2.2.

**Comment by kloczek** [comment]
Hmm I still don't see git tag for that version 🤔

**Comment by bmerry** [comment]
> Hmm I still don't see git tag for that version thinking

fakeredis has a new maintainer and a new repo. The tag is https://github.com/dsoftwareinc/fakeredis-py/releases/tag/v1.7.4

**Comment by kloczek** [comment]
https://github.com/dsoftwareinc/fakeredis-py/blob/9a8bfaa104c3a37f33c82310a01b30be26635c95/setup.cfg#L25-L30

And now latest `redis` is 4.3.1 https://github.com/redis/redis-py/tags
