### ISSUE TITLE
Bug: `hmset` mutates the dict upon storage

### ISSUE THREAD

**Issue by csojinb-picwell** [jamesls/fakeredis#74]
I noticed that `hmset` seems to mutate the hash that is passed in for storage. It looks like everything is being cast to a string on the input dict itself, instead of on a copy.

```
In [1]: conn = fakeredis.FakeStrictRedis()

In [2]: to_store = {'key': [123, 456]}

In [3]: conn.hmset('fake-key', to_store)
Out[3]: True

In [4]: to_store
Out[4]: {'key': '[123, 456]'}

```

This differs from the behavior of actual redis, which does not mutate the input dictionary

```
In [5]: conn = get_redis_connection()  # wired up to real redis

In [6]: to_store = {'key': [123, 456]}

In [7]: conn.hmset('fake-key', to_store)
Out[7]: True

In [8]: to_store
Out[8]: {'key': [123, 456]}
```

As you might imagine, this resulted in some very confusing test results.

**Comment by csojinb-picwell** [comment]
Offending line is here: https://github.com/jamesls/fakeredis/blob/master/fakeredis.py#L778

I'd submit a fix, but I found it right before I needed to head out for the night. Maybe in the morning.

**Comment by jamesls** [comment]
Thanks for reporting, this is now fixed.
