### ISSUE TITLE
Implement redis-py's .lock()

### ISSUE THREAD

**Issue by akshayjshah** [jamesls/fakeredis#79]
`fakeredis.FakeStrictRedis` doesn't implement [redis-py's .lock()](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L495) method. Are you open to a pull request that uses the standard lib's `threading.Lock` to fake the same behavior?

(Of course, I'll follow the contribution guidelines :)

**Comment by mansam** [comment]
Hey there, is there a reason this was closed without comment? I'm actually in need of the same thing.

**Comment by akshayjshah** [comment]
I found a workaround for my own use case; if there's some utility in a general solution, though, I'm happy to reopen and open a PR. Just waiting on @jamesls to weigh in.

**Comment by jamesls** [comment]
Sorry for the delay.  Definitely would be open to a PR that emulates redis-py's `lock()` method.

**Comment by akshayjshah** [comment]
Okay - I definitely won't have time to look at this again for a few weeks, but I can pick it up in early July.

**Comment by ze-phyr-us** [comment]
This would be very helpful. Have you had time to look at this @akshayjshah?

**Comment by akshayjshah** [comment]
As is probably obvious, I don't think I'm going to get to this (probably ever) - I've mostly stopped using Redis and fakredis. Up to @jamesls whether he'd like to close this issue, or whether it's worth keeping around.

**Comment by M1hacka** [comment]
+1 need this

**Comment by dhavenstein** [comment]
Need this !!
