### ISSUE TITLE
zadd() not working in FakeRedis

### ISSUE THREAD

**Issue by loisaidasam** [jamesls/fakeredis#83]
Apparently it's just adding the first key/value of `**kwargs` to the ZSet...

https://github.com/jamesls/fakeredis/blob/e7e0069914e0edcfc37eed6a3a7e64a00371a440/fakeredis.py#L1300-L1301

Any reason?

Also not returning the number of items added...

**Comment by loisaidasam** [comment]
How about uploading to PyPi?

**Comment by jamesls** [comment]
I was hoping to get a few more PR's merged into the next bug fix release, but they appear to involve more work than I expected so they'll probably have to wait for the next release.  I'll get a bug fix release out in the near future.

**Comment by loisaidasam** [comment]
Thanks @jamesls :+1:
