### ISSUE TITLE
Working with RQ

### ISSUE THREAD

**Issue by joeyespo** [jamesls/fakeredis#88]
It looks like RQ [doesn't work](https://github.com/nvie/rq/issues/282) with fakeredis. This is probably a concern of RQ, but thought I'd ask here to see what you think.

The problem is that RQ does something different when the connection is `Redis` vs `StrictRedis`, and uses `isinstance` to differentiate.

`FakeRedis` and `FakeStrictRedis` inherit from `object` directly, so this obviously won't work. Since all the methods are there, would it be possible to inherit from `Redis` and `StrictRedis` instead? All the behavior would still be masked, but now these classes can be dropped in wherever the superclasses are explicitly expected.

Sure, using `isinstance` isn't very Pythonic, but doing this would allow the fake classes to fit in more real-world cases. `Mock` objects do this too: `isinstance(Mock(int), int)  # => True`.

**Comment by bmerry** [comment]
I'm not comfortable changing the semantics of `isinstance(fake, redis.StrictRedis)` at this point: there is quite likely code that needs to behave differently depending on whether a fake or real redis is being used (e.g. to work around limitations/bugs in fakeredis), and changing the behaviour would cause it to think a real redis was being used.

I would suggest subclassing FakeStrictRedis in a way that makes the isinstance check work. It looks like mock does this by overriding `__class__`, although that seems like deep magic to me. You can probably also just create a class that derived from both FakeStrictRedis and StrictRedis.
