### ISSUE TITLE
Interaction of incr and mget does not match redis

### ISSUE THREAD

**Issue by bluemoo** [jamesls/fakeredis#99]
Redis returns the results of mget as a list of strings. In fakeredis, if you use incr and then mget, you get a list of integers, not strings.

Here's the bug in action (note the last item is a list containing an integer):
```
>>> import fakeredis
>>> cache = fakeredis.FakeStrictRedis()
>>> cache.incr('a', 1)
1
>>> cache.get('a')
'1'
>>> cache.incr('a', 1)
2
>>> cache.get('a')
'2'
>>> cache.mget(['a'])
[2]
```

Here's how it works against my redis instance:
```
>>> from django.core.cache import get_cache
>>> 
>>> redis_cache = get_cache('persistent').raw_client
>>> redis_cache.incr('a',1)
1
>>> redis_cache.get('a')
'1'
>>> redis_cache.incr('a',1)
2
>>> redis_cache.get('a')
'2'
>>> redis_cache.mget(['a'])
['2']
```

It looks like incr always transforms the item into an integer, but get works around it by calling to_bytes on the value before returning it. Perhaps the solution is to do the same on each item in mget.

**Comment by bluemoo** [comment]
I've put together a pull request with one possible approach to fixing this, if you're interested: https://github.com/jamesls/fakeredis/pull/100

**Comment by jamesls** [comment]
Closing out old issue, #100 has been merged.
